### Problem 45: Triangular, pentagonal, and hexagonal

# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:

# Triangle    Tn = n(n + 1) / 2   1, 3, 6,  10, 15, ...
# Pentagonal  Pn = n(3n − 1) / 2  1, 5, 12, 22, 35, ...
# Hexagonal   Hn = n(2n − 1)      1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

# Notes:

# For any n, Tn < Pn < Hn.

### Solution:

require 'set'

class Solver
  STARTING_INDEX = 286

  def self.find_solution
    print 'Searching'

    triangles = Set.new
    pentagonals = Set.new
    hexagonals = Set.new
    index = STARTING_INDEX

    loop do
      print '.' if (index - STARTING_INDEX) % 1000 == 0

      triangle = index * (index + 1) / 2
      triangles << triangle
      pentagonals << index * (3 * index - 1) / 2
      hexagonals << index * (2 * index - 1)

      if pentagonals.include?(triangle) && hexagonals.include?(triangle)
        puts ''
        puts "Found solution T#{index} with value #{triangle}"
        break
      end

      index += 1
    end
  end
end

Solver.find_solution

# Searching........................................................
# Found solution T55385 with value 1533776805
